### token
get http://localhost:5050/pickfun/device/MiddleWare/biz/getToken?uuid=blahblah


### logout
get http://localhost:5050/pickfun/device/MiddleWare/biz/logout


### update ip by id
get http://localhost:5050/pickfun/device/MiddleWare/biz/update?id=100&ip=192.168.0.254

### delete device by id
get http://localhost:5050/pickfun/device/MiddleWare/biz/deletedevice?id=100

### device list
get http://localhost:5050/pickfun/device/MiddleWare/biz/listLiveDevices


### report status
get http://localhost:5050/pickfun/device/MiddleWare/biz/report?id=100&status=1&lastMinutes=123


### get file
get http://localhost:5050/installer.exe


